---
title: "진행사항보고"
date: last-modified
date-format: "[Last Updated on] MMMM D, YYYY"
format: html
---

## 폭염 사망 영향 논문
-   **ISEE: POSTER DISCUSSION 07** (September 20, 2023 / 10:45:00 AM - 12:15:00 PM): 5 minute on poster board presentation, including Q&A**(포스터 작성, 진행 중)**
-   **JKMS 재제출(완료, Under Review)**






## 미세먼지과제
-   **서울시 하이브리드 대기오염물질 모델링을 적용한 단기건강영향 분석**
    + 2017 ~ 2019년 동별 데이터 확보 **(완료)**
    + 노출 매핑 분석 **(완료)**
    + 건강 영향 분석 **(진행중)**






## 기후보건과제
-   **중기추진과제도출**
    + 한국 기후보건 연구 논문 1차 평가 **(완료)**
    + 한국 기후보건 연구 논문 2차 평가 **(진행중)**
      + 검색식 보완, DB 보완하여 분석 수행
      + 보완된 DB 분석을 통해 미래과제 필요성 및 시사점 추가 도출
      





## 극한기후과제
-   집중호우 이벤트 기간과 질병코드 전달**(완료)**
-   2020년도 집중호우 이벤트 - 사망 관계 예시 분석**(완료)**
-   집중호우 이벤트 ~ 사망 분석 (BSTS, DLNM 모델) **(진행중)**
-   NHIS, NEDIS 데이터 waiting**(진행중)**
- 한국역학회 추계학술대회 포스터 발표
  + 초록제출**(완료)**, 포스터 작성**(진행중)**
  + 학술대회 일정 / 장소: 9월 15일 / 스위스그랜드호텔 그랜드볼룸







## 수면 논문
-   학생에게 추가 관련자료 수신(완료)
-   **수정 진행중(진행 중)**
  + 타겟저널: Pediatric and perinatal epidemiology






## 전자파과제
-   **서베이몽키: 설문문항 정리 등(완료)**
-   스마트워치: 측정대상자수 확인메일 보내기(완료)
-   **한국전자파학회 하계종합학술대회 발표**: 2023년 8월 23일(수) / 델피노리조트(강원도 고성군 토성면 미시령옛길 1153)**(진행 중)**
-   **ISEE 포스터: 코첸스 임신중 휴대전화 사용에 따른 임신결과(성향점수 이용)**
    + 초록제출**(완료)**



## 논문주제1: 국내에서 연령 표준화 했을 때, 초미세먼지에 따른 질병부담(초과사망) 추정
 - [GBD 2019 데이터 리소스](https://ghdx.healthdata.org/gbd-2019)
  + 초미세먼지IER 커브 데이터: [Global Burden of Disease Study 2019 (GBD 2019) Particulate Matter Risk Curves](https://ghdx.healthdata.org/record/ihme-data/global-burden-disease-study-2019-gbd-2019-particulate-matter-risk-curves)
  + [란싯논문](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30752-2/fulltext)
 - [PM2.5 IER function 파라메터 관련 내용](https://github.com/ITHIM/ITHIM-R/issues/2)
 - [R에서 연속형노출 RR function 이 주어졌을 때 PAF 산출](https://github.com/INSP-RH/pifpaf/tree/master)
 
 
 
 
 
 
## 논문주제1: 폭염에 따른 외인사망 영향
 - 주제: 폭염이 외인사망(external mortality)에 미치는 영향 (열대야 영향으로 다음날 액티비티에 영향)
 - [단순확인 분석결과](https://www.dropbox.com/scl/fi/6zzxgrm2bltskqakknu96/death_tot.xlsx?rlkey=vccflfjnbwjlyy3zpfhkv8vlc&dl=0)





## 기타
-   예방의학 및 실습 강의
-   [예방의학교실 학생 선택실습 일정](https://www.dropbox.com/s/f9vvrmn89g0x3jg/2023%20%EB%B3%B8%EA%B3%BC4%ED%95%99%EB%85%84%20%EC%98%88%EB%B0%A9%EC%9D%98%ED%95%99%EA%B3%BC%20%EC%84%A0%ED%83%9D%EC%8B%A4%EC%8A%B5%20%EC%9D%BC%EC%A0%95_v1.hwp?dl=0)
-   휴가: 8월 28일 \~ 9월 1일
-   충남 감염병관리지원단
    + **코로나19 PCC 논문 억셉트(완료)**
    + 예비방역인력양성교육 3기 (8월 25일, 보령시 쏠레드 호텔 2층 블리스)
    + FETP-F 담당자 교육 2단계 (9월월 11일, 과제지도 및 수인성역학조사 절차 강좌)
- **임연희 교수님 WHO 출판물 중 미세먼지 감축으로 인한 경제적 SAVE 효과 관련 출판물 찾기**
- 단국대 통계지원팀
    + 현정근교수님: 분석하여 지속 전달 중. npj Regenerative Medicine 제출**(완료)**, 리비전**(진행중)**












## 코로나19판데믹 영향 논문
-   WHO 방법론 리뷰
    -   [WHO 논문](https://www.nature.com/articles/s41586-022-05522-2#Sec6)
    -   [WHO 결과 파일](https://www.who.int/data/sets/global-excess-deaths-associated-with-covid-19-modelled-estimates)
    -   [WHO 방법론 레퍼런스](https://cdn.who.int/media/docs/default-source/world-health-data-platform/covid-19-excessmortality/who_methods_for_estimating_the_excess_mortality_associated_with_the_covid-19_pandemic.pdf?sfvrsn=5a05fa76_2&download=true)
        -   **데이터**: For this study, our main sources of data are reports of ACM as collected and reported by countries' relevant institutions -- from national statistics offices, ministries of health, population registries, etc. These have been collected in several repositories such as the data routinely shared with WHO as part of its standing agreement with member states, Eurostat, The Human Mortality Database (HMD) as part of the Short-Term Mortality Fluctuations (STMF) project (Nemeth, Jdanov, and Shkolnikov ´ , 2021) and the World Mortality Dataset (WMD), as described in Karlinsky and Kobak (2021).
        -   **covariates**
            -   a high income country binary indicator
            -   COVID-19 test positivity rate
            -   COVID-19 death rate
            -   temperature
            -   population density
            -   sociodemographic index (SDI)
            -   human development index (HDI)
            -   stringency (index for lockdown restrictions and closures)
            -   overall government response
            -   economic (including measures such as income support and debt relief)
            -   containment (combines lockdown restrictions and closures)
            -   historic non-communicable disease rates
            -   historic cardiovascular disease rate
            -   historic HIV rate
            -   historic diabetes prevalence
            -   life expectancy
            -   proportion of the population under-15
            -   proportion of the population over-65
        -   **모델링** 방법
            -   Deriving expected mortality for years 2020 and 2021
                -   Those that have historic **monthly** ACM data (100 countries)
                    -   대개 2015-2019년 기간 데이터에 기반
                    -   outcome distribution: negative binomial
                    -   yealy trend: a thin-plate spline
                    -   within-year seasonal variation: a cyclic cubic spline
                    -   the `gam` function in the `mgcv` package
                    -   spline model은 각 나라별로 fitted됨.
                -   Those that have historic **annual** ACM data only (94 countries)
                    -   대개 2000-2019년 기간 데이터에 기반
                    -   이전모델에서 monthly term을 제외함 (i.e., a spline in year)
                    -   월별로 사망을 배분하기 위해서, 월별 기온과 사망의 관계를 이용해서 배분함.
